# fly.toml app configuration file generated for lexsy-ai on 2025-09-15T22:14:06+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'lexsy-ai'
primary_region = 'lax'

[build]
  dockerfile = 'Dockerfile'

[env]
  NEXT_PUBLIC_API_BASE = 'https://lexsy-safe-api.fly.dev'
  PORT = '3000'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [[http_service.checks]]
    interval = '30s'
    timeout = '5s'
    grace_period = '10s'
    method = 'GET'
    path = '/'

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
